### ISSUE TITLE
 java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow

### ISSUE THREAD

**Issue by vulegend** [cloudinary/cloudinary_android#34] opened 2017-10-31 03:44 UTC
10-31 04:42:32.416 16248-17032/com.tapp.hookapp E/CursorWindow: Failed to read row 0, column 0 from a CursorWindow which has 0 rows, 22 columns.
10-31 04:42:32.417 16248-17032/com.tapp.hookapp E/JobStorage: could not load all jobs
                                                              java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                  at android.database.CursorWindow.nativeGetLong(Native Method)
                                                                  at android.database.CursorWindow.getLong(CursorWindow.java:524)
                                                                  at android.database.CursorWindow.getInt(CursorWindow.java:591)
                                                                  at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
                                                                  at com.evernote.android.job.JobStorage.getAllJobRequests(JobStorage.java:189)
                                                                  at com.evernote.android.job.JobManager.getAllJobRequests(JobManager.java:289)
                                                                  at com.evernote.android.job.JobRescheduleService.onHandleWork(JobRescheduleService.java:71)
                                                                  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:386)
                                                                  at android.support.v4.app.JobIntentService$CommandProcessor.doInBackground(JobIntentService.java:377)
                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                  at java.lang.Thread.run(Thread.java:762)

I get this 2-4 seconds in after calling MediaManager.init function, and on every action through MediaManager. Any clue why this happens and how i could fix it. Thanks

**Comment by roeeba** [comment] 2017-11-15 07:45
Hi @vulegend. Could you please share with us the following information:

1. Your Init code.
2. Your upload code.
3. Which device are you using?
4. Your Android version.
5. Did you try running it on a different device? 

This will help us reproduce the issue on our end. Thanks.

**Comment by roeeba** [comment] 2018-02-19 09:27
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-02-19 09:27 UTC
Labels: question
