### ISSUE TITLE
Cloudinary Upload unable to use URI from contentproviders such as google photos

### ISSUE THREAD

**Issue by nigelbro** [cloudinary/cloudinary_android#48] opened 2018-01-18 15:38 UTC
When using a Uri from a photo selected from google photos (None local to device) the sdk is unable to handle this. The sdk should be able to handle any valid Uri passed to it. 

17004-19936/com.bump.bumpapp E/DefaultRequestProcessor: LocalUriNotFoundException for request 115d437b-5acc-4772-9b9b-b3998f23d47c.
                                                                           com.cloudinary.android.payload.LocalUriNotFoundException: Uri file:///content%3A/com.google.android.apps.photos.contentprovider/0/1/... could not be found
                                                                               at com.cloudinary.android.payload.LocalUriPayload.prepare(LocalUriPayload.java:43)
                                                                               at com.cloudinary.android.DefaultRequestProcessor.doProcess(DefaultRequestProcessor.java:169)
                                                                               at com.cloudinary.android.DefaultRequestProcessor.processRequest(DefaultRequestProcessor.java:90)
                                                                               at com.cloudinary.android.MediaManager.processRequest(MediaManager.java:367)
                                                                               at com.cloudinary.android.AndroidJobStrategy$UploadJob.onRunJob(AndroidJobStrategy.java:260)
                                                                               at com.evernote.android.job.Job.runJob(Job.java:121)
                                                                               at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:165)
                                                                               at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:150)
                                                                               at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:133)
                                                                               at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                               at java.lang.Thread.run(Thread.java:762)

**Comment by roeeba** [comment] 2018-01-21 13:09
Hi @nigelbro. Could you please share with us the steps to reproduce the issue?

1. How do you get the URI?
2. How do you pass it to MediaManager upload method?
3 Do you have any storage permissions set?

You can refer to our sample app, this flow in specific:
https://github.com/cloudinary/cloudinary_android/blob/bd8c75d17eea1176cc9575335aeb84ee78e3a04c/sample/src/main/java/com/cloudinary/android/sample/app/MainActivity.java#L247

**Comment by roeeba** [comment] 2018-02-19 09:29
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-02-19 09:29 UTC
Labels: question
