### ISSUE TITLE
E/DefaultRequestProcessor: Unexpected exception for request 962e6fd9-ea00-4d9e-8db0-43784a23ea48.  java.lang.RuntimeException: Upload preset not found

### ISSUE THREAD

**Issue by vikasnikam** [cloudinary/cloudinary_android#41] opened 2017-11-24 05:36 UTC
Unexpected exception for request 962e6fd9-ea00-4d9e-8db0-43784a23ea48.
                                                                                   java.lang.RuntimeException: Upload preset not found
                                                                                       at com.cloudinary.android.UploaderStrategy.callApi(UploaderStrategy.java:143)
                                                                                       at com.cloudinary.Uploader.callApi(Uploader.java:34)
                                                                                       at com.cloudinary.Uploader.uploadLargeParts(Uploader.java:212)
                                                                                       at com.cloudinary.Uploader.uploadLarge(Uploader.java:143)
                                                                                       at com.cloudinary.android.DefaultRequestProcessor.doProcess(DefaultRequestProcessor.java:197)
                                                                                       at com.cloudinary.android.DefaultRequestProcessor.processRequest(DefaultRequestProcessor.java:89)
                                                                                       at com.cloudinary.android.MediaManager.processRequest(MediaManager.java:367)
                                                                                       at com.cloudinary.android.AndroidJobStrategy$UploadJob.onRunJob(AndroidJobStrategy.java:203)
                                                                                       at com.evernote.android.job.Job.runJob(Job.java:109)
                                                                                       at com.evernote.android.job.JobExecutor$JobCallable.runJob(JobExecutor.java:151)
                                                                                       at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:136)
                                                                                       at com.evernote.android.job.JobExecutor$JobCallable.call(JobExecutor.java:119)
                                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by roeeba** [comment] 2017-11-24 13:31
Hi, @vikasnikam. In order to better understand the issue, we need some more information. Can you please share with me the following?

* Execution flow: how to reproduce the issue?
* Code causing the error.

Thanks

**Comment by roeeba** [comment] 2018-02-01 14:12
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2018-02-01 14:12 UTC
Labels: question
