### ISSUE TITLE
 java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.

### ISSUE THREAD

**Issue by nigelbro** [cloudinary/cloudinary_android#36] opened 2017-11-09 01:29 UTC
E/JobStorage: could not load all jobs
                                                              java.lang.IllegalStateException: Couldn't read row 0, col 0 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it.
                                                                  at android.database.CursorWindow.nativeGetLong(Native Method)
                                                                  at android.database.CursorWindow.getLong(CursorWindow.java:524)
                                                                  at android.database.CursorWindow.getInt(CursorWindow.java:591)
                                                                  at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:69)
                                                                  at com.evernote.android.job.JobStorage.getAllJobRequests(JobStorage.java:152)
                                                                  at com.evernote.android.job.JobManager.getAllJobRequests(JobManager.java:274)
                                                                  at com.cloudinary.android.AndroidJobStrategy.getPendingImmediateJobsCount(AndroidJobStrategy.java:152)
                                                                  at com.cloudinary.android.DefaultRequestDispatcher.dispatch(DefaultRequestDispatcher.java:27)
                                                                  at com.cloudinary.android.UploadRequest.dispatch(UploadRequest.java:130)

This is my stacktrace when trying dispatch an upload using the sdk. I am running gradle 3+ im new to using cloudinary and it sucks the first time I use it, it doesnt work!

**Comment by nigelbro** [comment] 2017-11-09 23:38
I have also opened the following issue with evernote library that you guys are using . this is the issue link 
https://github.com/evernote/android-job/issues/316

**Comment by roeeba** [comment] 2017-11-13 10:21
Hi @nigelbro. Could you please share with us the following information:

1. Your Init code. 
2. Your upload code. 
3. Which device are you using?
4. Your Android version. 
5. Did you try running it on a different device?

This will help us reproduce the issue on our end. Thanks.

**Comment by nigelbro** [comment] 2017-11-13 12:27
Init Code: `override fun onCreate() {
        super.onCreate()
        instance = this
        startRemoteSyncJob()
        Fabric.with(this, Crashlytics())
        var cloudinaryConfig = HashMap<String, String>()
        cloudinaryConfig.put(CLOUD_NAME_KEY, CLOUD_NAME_VALUE)
        MediaManager.init(this,cloudinaryConfig)
        component = DaggerAppComponent.builder().appModule(AppModule(this)).actionsCreatorModule(ActionsCreatorModule()).storeModule(StoreModule()).build()

    }`

upload Code: `bitmaps!!.forEach {
            val stream = ByteArrayOutputStream()
            it.compress(Bitmap.CompressFormat.JPEG, 100, stream)
            val byteArray = stream.toByteArray()
            MediaManager.get().upload(byteArray)
                    .unsigned("item_img")
                    .callback(object : UploadCallback {
                        override fun onProgress(requestId: String?, bytes: Long, totalBytes: Long) {

                        }

                        override fun onStart(requestId: String?) {
                        }

                        override fun onSuccess(requestId: String?, result: MutableMap<Any?, Any?>?) {
                            newItem.images.add(result!!.getValue("url") as String)
                        }

                        override fun onError(requestId: String?, error: ErrorInfo?) {
                            Log.i("ERR", "ERROR")
                        }

                        override fun onReschedule(requestId: String?, error: ErrorInfo?) {
                            Log.i("ERR", "ERROR")
                        }
                    }).dispatch()
        }`

Android Version 7.1.1 Galaxy Note 8 . 

Did I try running on a different device : My note 8 and my s8 plus. I have an s7 also I will attempt to run on

**Comment by roeeba** [comment] 2017-11-14 12:48
Thanks for the additional info, @nigelbro. While we didn't manage to reproduce this on our end, could you please try running a clean empty project with nothing but cloudinary and see if it works for you? If it works then something in your project might not playing well with Cloudinary/evernote. 

If you can share your build.gradle file we can recreate the same dependency tree ourselves and try to detect which other dependency causes the problem (if it's indeed a dependency issue).

**Comment by nigelbro** [comment] 2017-11-14 12:51
Sure

**Comment by nigelbro** [comment] 2017-11-23 12:28
Working on this today to test

**Comment by nigelbro** [comment] 2017-11-23 15:06
So with creating a boiler plate application the sdk is working. It also changed from using the .upload(byte[]) to using the .upload(uri) instead and that is actually now working in my application. Maybe some issue with the upload(byte[])

**Comment by nigelbro** [comment] 2017-11-23 15:10
This is good to close unless you want to leave it open to investigate the upload(byte[]) signature. But before you close is there a way to make a synchronous upload request?

**Comment by roeeba** [comment] 2017-11-28 09:01
You can call the basic Cloudinary uploader, it's still in there and it's synchronous:

`MediaManager.get().getCloudinary().uploader().upload(...)`

Note that there's no phone state and policies involved this way, and it's using the old API for parameters and options. It works well nonetheless.

**Comment by roeeba** [comment] 2017-12-18 12:12
Closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.

**Closed by roeeba** 2017-12-18 12:12 UTC
Labels: question
