### ISSUE TITLE
Targeting S+ (version 31 and above)

### ISSUE THREAD

**Issue by vasudevjogani** [cloudinary/cloudinary_android#137] opened 2022-02-15 10:22 UTC
E/JobProxy14: com.app.xyz: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.

**Comment by adimiz1** [comment] 2022-02-15 13:14
Hi @vasudevjogani 
We plan to release a new major version for the Android SDK by Sunday, If you want to submit a PR for us to review with the change by then we can put it into this release feel free to do so

**Comment by isles1217** [comment] 2022-06-30 19:33
Hey there! I'm still seeing these errors on version 2.2.0. Any chance you could revisit this issue? Thanks!


```
E/JobProxy14: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
    java.lang.IllegalArgumentException: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at com.evernote.android.job.v14.JobProxy14.getPendingIntent(JobProxy14.java:199)
        at com.evernote.android.job.v14.JobProxy14.cancel(JobProxy14.java:162)
        at com.evernote.android.job.JobProxy$Common.cleanUpOrphanedJob(JobProxy.java:285)
        at com.evernote.android.job.JobManager.schedule(JobManager.java:188)
        at com.evernote.android.job.JobRequest.schedule(JobRequest.java:430)
        at com.cloudinary.android.AndroidJobStrategy.doDispatch(AndroidJobStrategy.java:99)
        at com.cloudinary.android.DefaultRequestDispatcher.dispatch(DefaultRequestDispatcher.java:54)
        at com.cloudinary.android.UploadRequest.doDispatch(UploadRequest.java:245)
        at com.cloudinary.android.UploadRequest.dispatch(UploadRequest.java:202)
        at com.cloudinary.android.UploadRequest.dispatch(UploadRequest.java:170)
```

**Comment by michalkcloudinay** [comment] 2022-07-03 14:29
Hi @isles1217,

Can you please let us know if this is happening when running the sample project?  Or when implementing the SDK in your project?

**Comment by isles1217** [comment] 2022-07-03 15:26
I'm seeing this error when interesting the SDK into my project. Thanks!

**Comment by michalkcloudinay** [comment] 2022-07-03 16:02
Thanks for getting back.

We are unable to reproduce this issue on our end. Can you please provide me with the line in the code that pops this warning? Also, can you please make sure that the build.gradle / pom.xml file is synced after updating the latest version of the Cloudinary SDK? 
Looking forward to your updates,
Thanks
Michal

**Comment by isles1217** [comment] 2022-07-05 21:38
Hi Michal,

Version `2.2.0` was just integrated into our project and is the first/only version of the SDK, so my `build.gradle` file is definitely up-to-date. Based on the stacktrace, I'm guessing the issue is that the Cloudinary SDK seems to be using Evernote's Deprecated `JobManager` SDK, which, according to its own [Github readme](https://github.com/evernote/android-job), shouldn't be used anymore. Are you able to estimate how long it might take to migrate to `WorkManager` instead?

Here's the calling code:

```
            MediaManager.get()
                .upload(fileUri)
                .options(options)
                .callback(
                    object : UploadCallback {
                        override fun onStart(requestId: String?) {
                            (...)
                        }

                        override fun onProgress(requestId: String?, bytes: Long, totalBytes: Long) {
                            (...)
                        }

                        override fun onSuccess(
                            requestId: String?,
                            resultData: MutableMap<Any?, Any?>?
                        ) {
                            (...)
                        }

                        override fun onError(requestId: String?, error: ErrorInfo?) {
                            (...)
                        }

                        override fun onReschedule(requestId: String?, error: ErrorInfo?) {
                            (...)
                        }
                    }
                )
                .dispatch()
```

**Comment by dimaportenko** [comment] 2022-08-23 12:46
Any updates here? I have the same issue. Sounds like it should be a simple fix for the new android target release. Something like https://stackoverflow.com/questions/67045607/how-to-resolve-missing-pendingintent-mutability-flag-lint-warning-in-android-a

**Comment by dimaportenko** [comment] 2022-08-23 15:50
I think I solved my issue by adding `resource_type` option 
```
...
      uploadRequest
          .unsigned(presetName)
          .option("resource_type", getResourceType(params.getString("type")))
...
```

**Comment by victorli-cloudinary** [comment] 2022-08-24 22:00
Thanks for the update @dimaportenko. @isles1217 can you try the above?

**Comment by isles1217** [comment] 2022-09-14 01:21
@victorli-cloudinary that didn't help me. the issue isn't that the upload isn't working, but that it's using deprecated libraries, and poses a risk that it could break on newer Android OS versions. Any update as to when this will be fixed and when the updated SDK will be available?

**Comment by isles1217** [comment] 2022-10-25 21:14
It looks like this issue can be closed. Thanks! 🎉

**Closed** 2022-10-26 07:57 UTC
